### ISSUE TITLE
Resolve Page build and deployment errors

### ISSUE THREAD

**Issue by selwynpolit** [WebFirstInc/drupalstudyguide#10]
I fixed this in my repo:

If the build causes a third action to run on Github and fails:
you need to change the deployment settings to a custom action.
Repo -> Settings -> Pages -> Build and deployment -> Source -> GitHub Action.
This should disable the standard page deployment process.

@WebFirstInc I don't have permissions to fix this..

**Comment by samuelmolinski** [comment]
Thanks @selwynpolit! We are working to update permissions for a few users to make this change.
